# H2 em memoria
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Cria as tabelas automaticamente pelo JPA
spring.jpa.hibernate.ddl-auto=create-drop

# Console visual do H2 (opcional, mas util)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# mysql
#conexao
# spring.datasource.url=jdbc:mysql://localhost:3306/base
# spring.datasource.username=root
# spring.datasource.password=root
# #comandos
# spring.jpa.hibernate.ddl-auto=create
# spring.jpa.show-sql: true

#logging.level.org.hibernate.SQL=debug
#logging.level.org.hibernate.type.descriptor.sql=trace

#configuracao JWT
jwt.secret = VKF.x8zKYvfnK%G(F[B/
jwt.expiration = 600000
